// Simpla reguli nur trovota ye vortlimiti

// FACOR: inteligenta *matcheso

simplaReguli = {
    "–": "-",
    "=2 |[[Arkivo:": "| Imajo = [[Arkivo:",
    "aktorino di cinemo": "cinem-aktorino",
    "aktoro di cinemo": "cinem-aktoro",
    "aktorulo": "aktoro",
    "aktorulo di cinemo": "cinem-aktorulo",
    "!align=right|Guvernisteso:": "| Guvernisteso = ",
    "!align=right|Precedanto:": "| Precedanto1 = ",
    "!align=right|Sucedanto:": "| Sucedanto = ",
    "an autori": "ana skriptisti",
    "anoncis": "anuncis",
    "asistis": "frequentis",
    "automobilo-kontestisto": "automobilisto",
    "autorino": "skriptisto",
    "autoritatema": "autoritatoza",
    "autoro": "skriptisto",
    "autorulo": "skriptisto",
    "bazita en": "apogata sur",
    "bovari": "bovaro",
    "boviari": "bovaro",
    "Britan": "Britanian",
    "Britanii": "Britaniani",
    "California": "Kalifornia",
    "Category:": "Kategorio:",
    "chefa ministri": "chefministri",
    "chefministri di Sri Lanka": "chefa ministri di Sri Lanka",
    "chefministro di Peru": "chefa ministro di Peru",
    "{{Ciencisto": "{{Biografio",
    "{Ciencisto|": "{Biografio",
    "cinemo-direktisto": "filmifisto",
    "datizas de": "evas de",
    "defendar": "defensar",
    "defendas": "defensas",
    "dekyar": "yardek",
    "de plus": "pose",
    "deskribas": "deskriptas",
    "deskribita": "deskriptita",
    "deskribita": "deskriptita",
    "diferenta": "diferanta",
    "di guvernisteso": "dil ofico",
    "di lua populo": "di lua habitantaro",
    "direktisto di cinemo": "filmifisto",
    "disputo": "konkurso",
    "distanco": "disto",
    "domo-maestro": "domo-chefo",
    "ed ek tota la habitantaro": "ed ek omna habitantaro",
    "Ek la tota habitantaro": "Ek omna habitantaro",
    "ekonomiala aktivesi": "ekonomial agadi",
    "ekonomikala aktivesi": "ekonomial agadi",
    "elektrikala": "elektrala",
    "eligita": "elektita",
    "en homajo a": "memoriganta",
    "e nove": "ed itere",
    "en quo": "ube",
    "fiziologisto": "fiziologiisto",
    "fluvio]]": "",
    "fondisto": "fondinto",
    "formacesas da": "konsistas ek",
    "formas": "formacas",
    "formesis": "formacesis",
    "Formulo 1ma": "Formulo 1",
    "fotografio": "fotografo",
    "frequenta": "ofta",
    "generale": "ordinare",
    "Germaniana": "Germana",
    "gradoze": "gradope",
    "Granda Nordeyo-Milito": "Granda Nordala Milito",
    "graviteso": "gravitado",
    "greca": "Greka",
    "Gregoriana": "Gregoriala",
    "guvernio": "guvernerio",
    "guverno": "guvernerio",
    "habitesis per singla individui": "de omna hemanari vivis unika sola individuo, e",
    "havas libera imajo.jpg": "havas libera imajo.svg",
    "hemisfero": "misfero",
    "Ica esas": "Yen",
    "ico esas": "yen",
    "Image:": "Arkivo:",
    "Imajo:": "Arkivo:",
    "imediate": "nemediate",
    "importas": "importacas",
    "Indijena amerikana": "indijeni Amerikana",
    "inflacio]": "inflaciono]",
    "Inflacio": "Inflaciono",
    "informala": "neformala",
    "interakto": "interago",
    "io:p": "io:P",
    "Islama": "Islamala",
    "Islama]": "Islamana]",
    "Islama Stato": "Islamana Stato",
    "Juliana": "Juliala",
    "kantistulo": "kantisto",
    "kardenali": "kardinali",
    "ke okazis": "qua eventis",
    "kombusteblajo": "fuelo",
    "kompletis": "kompletigis",
    "konocita kam": "konocita kom",
    "konquist": "konquest",
    "konstitucata da": "konstitucata per",
    "konstruita": "konstruktita",
    "kontinu": "dur",
    "kontrakto": "kontrato",
    "kontrapapo": "kontrepapo",
    "kun bomb": "per bomb",
    "Lasta-Diala Santi": "Lasta-Dia Santi",
    "Latinal Amerikani": "Latin-Amerikani",
    "Latin Amerika": "Latinida Amerika",
    "laureato en": "laureato pri",
    "la [[Usana": "l'[[Usana",
    "lojanti": "habitanti",
    "lojanto-denseso": "denseso di habitantaro",
    "Malgre ol": "Quankam ol",
    "manjaji": "nutrivi",
    "maxima extenso": "maxima ampleso",
    "maxim grava": "maxim importanta",
    "Medicino e Fiziologio": "Fiziologio o Medicino",
    "mezala denseso": "mezvalora denseso",
    "mezala": "mezvalora",
    "mez-valora": "mezavalora",
    "mikrabiologiisto": "mikrobiologiisto",
    "militas kontra": "militas kontre",
    "militis kontra": "militis kontre",
    "mixuri": "mixi",
    "mortita": "mortinta",
    "mulieri 18 yari": "mulieri evante 18 yari",
    "Navarra": "Navara",
    "Navarre": "Navara",
    "nedependenta": "nedependanta",
    "Nederlanda": "Nederlandana",
    "ne-employeso": "chomeso",
    "Ne havas imajo en Commons": "[[Arkivo:Ne havas libera imajo.svg|180px]]",
    "nexta": "sequanta",
    "Nexta": "Sequanta",
    "Nijeria": "Nigeria",
    "{{Nobel-laureati en": "{{Nobel-laureati pri",
    "nomata": "nomizita",
    "nomesita": "nomizita",
    "nomita": "nomizita",
    "nove": "itere",
    "okazis": "eventis",
    "okuras": "eventas",
    "okuris": "eventis",
    "omna yari": "omnayare",
    "ordinatr": "komputer",
    "Pacifika Insulana": "Pacifik insulani",
    "Pacifik insulani": "Pacifik-insulani",
    "partoprenis a": "apartenis a",
    "permezas": "permisas",
    "perzono": "persono",
    "piloto": "pilotisto",
    "plu di": "plu kam",
    "pluveso": "pluvozeso",
    "populaciono": "habitantaro",
    "por homini": "por la mulieri",
    "Portuo Riko": "Porto-Riko",
    "por unesma foyo": "unesma-foye",
    "= p": "= P",
    "predominanta": "dominacanta",
    "prencipua": "precipua",
    "presenco": "prezenteso",
    "prezenti": "prizenti",
    "proponis": "propozis",
    "psikiatro": "psikiatriisto",
    "publikis": "publikigis",
    "quanto di pluvo": "pluvozeso",
    "qui evas": "evante",
    "rebelionis": "revoltis",
    "rebeliono": "rebeleso",
    "referendumo": "plebicito",
    "rejado di": "regno di",
    "religiono": "religio",
    "renoncis": "renuncis",
    "reporto": "raporto",
    "reprizenta": "reprezenta",
    "revenuo por familio esas": "revenuo per familio esis",
    "rezigna": "renunca",
    "Richter-skalo": "skalo di Richter",
    "rinominesas": "rinomizesas",
    "romantismo": "Romantikismo",
    "Santo Paulus": "Santa Paulus",
    "Sao Tome": "San-Tome",
    "Saudia Arabia": "Saudi-Arabia",
    "Segun [[Usana": "Segun l'[[Usana",
    "senatori": "senatani",
    "senator": "senatano",
    "sociologiisto": "sociologo",
    "Sovietana": "Sovietiana",
    "speciala": "specala",
    "speciale": "specale",
    "stadiono": "stadio",
    "stadiono": "stadio",
    "substitucas": "remplasas",
    "substitucis": "remplasis",
    "Sud-Afrika": "Sudafrika",
    "sufris intensa": "subisis intensa",
    "&sup2;": "²",
    "Timor-Leste": "Estal Timor",
    "tota la": "omna",
    "transformaces": "transformes",
    "Ukrainia": "Ukraina",
    "Unioninta Nacioni": "Unionita Nacioni",
    "Unioninta Povi": "westala federiti",
    "Unioninta Rejio": "Unionita Rejio",
    "Unionita Povi": "[[Federiti de la duesma mondomilito|la Federiti]]",
    "UsanaStati|": "Provinci stati kantoni",
    "vaporo-mashin": "vaporomashin",
    "veloceso": "rapideso",
    ":''Videz anke: [[": "{{PA|",
    "volleyball": "volebalo",
    "Weimar Republiko": "Weimar-Republiko",
    "ye [[": "en [[",
    "Ye": "En",
}
